version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Package & Dependicies are getting installed"
      - npm -f install
      - echo "Packages have been installed"
      - echo "Storing Build Artifact to the Location"
artifacts:
  type: zip
  paths:
    - '*'
